<?php

namespace Database\Seeders;

use App\Models\Jurisdictions;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class JurisdictionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $jurisdictions = [
            [
                'address1' => '1553 Quarry Drive',
                'address2' => '',
                'city' => 'Montgomery',
                'province' => 'Alabama',
                'province_code' => 'AL',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '36117',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '2345 Blackwell Street',
                'address2' => '',
                'city' => 'Wasilla',
                'province' => 'Alaska',
                'province_code' => 'AK',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '99654',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => 'Pago Plaza Building',
                'address2' => '',
                'city' => 'Pago Pago',
                'province' => 'American Samoa',
                'province_code' => 'AS',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '96799',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '663 Elmwood Avenue',
                'address2' => '',
                'city' => 'Scottsdale',
                'province' => 'Arizona',
                'province_code' => 'AZ',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '85253',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '2279 Green Hill Road',
                'address2' => '',
                'city' => 'Glenwood',
                'province' => 'Arkansas',
                'province_code' => 'AR',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '71943',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '267 Ashcraft Court',
                'address2' => '',
                'city' => 'LOS ANGELES',
                'province' => 'California',
                'province_code' => 'CA',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '90001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '2230 McKinley Avenue',
                'address2' => '',
                'city' => 'Byers',
                'province' => 'Colorado',
                'province_code' => 'CO',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '80103',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '2287 Hott Street',
                'address2' => '',
                'city' => 'AVON',
                'province' => 'Connecticut',
                'province_code' => 'CT',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '06001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '4003 Maud Street',
                'address2' => '',
                'city' => 'Philadelphia',
                'province' => 'Delaware',
                'province_code' => 'DE',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '19146',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '1386 Coolidge Street',
                'address2' => '',
                'city' => 'Orlando',
                'province' => 'Florida',
                'province_code' => 'FL',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '32810',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '1128 Geraldine Lane',
                'address2' => '',
                'city' => 'AVONDALE ESTATES',
                'province' => 'Georgia',
                'province_code' => 'GA',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '30002',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '5016 Hanifan Lane',
                'address2' => '',
                'city' => 'Agana',
                'province' => 'Guam',
                'province_code' => 'GU',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '96932',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '4861 Randall Drive',
                'address2' => '',
                'city' => 'Hilo',
                'province' => 'Hawaii',
                'province_code' => 'HI',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '96720',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '3206 Seltice Way',
                'address2' => '',
                'city' => 'Coeur D Alene',
                'province' => 'Idaho',
                'province_code' => 'ID',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '83814',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '337 Scenic Way',
                'address2' => '',
                'city' => 'Mattoon',
                'province' => 'Illinois',
                'province_code' => 'IL',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '61938',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '3180 Overlook Drive',
                'address2' => '',
                'city' => 'Colfax',
                'province' => 'Indiana',
                'province_code' => 'IN',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '46035',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '1393 Park Boulevard',
                'address2' => '',
                'city' => 'Casey',
                'province' => 'Iowa',
                'province_code' => 'IA',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '50048',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '2627 Williams Lane',
                'address2' => '',
                'city' => 'Wichita',
                'province' => 'Kansas',
                'province_code' => 'KS',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '67202',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '2077 Coffman Alley',
                'address2' => '',
                'city' => 'Oak Grove',
                'province' => 'Kentucky',
                'province_code' => 'KY',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '42223',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '1017 Willow Oaks Lane',
                'address2' => '',
                'city' => 'Lafayette',
                'province' => 'Louisiana',
                'province_code' => 'LA',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '70506',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '3036 Victoria Court',
                'address2' => '',
                'city' => 'Jonesboro',
                'province' => 'Maine',
                'province_code' => 'ME',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '04648',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => 'Ebeye',
                'address2' => '',
                'city' => 'Ebeye',
                'province' => 'Marshall Islands',
                'province_code' => 'MH',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '96970',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '1534 Cambridge Place',
                'address2' => '',
                'city' => 'Baltimore',
                'province' => 'Maryland',
                'province_code' => 'MD',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '21231',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '561 C Street',
                'address2' => '',
                'city' => 'Framingham',
                'province' => 'Massachusetts',
                'province_code' => 'MA',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '01702',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '3274 Cunningham Court',
                'address2' => '',
                'city' => 'Bloomfield Township',
                'province' => 'Michigan',
                'province_code' => 'MI',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '48302',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => 'Office of the President',
                'address2' => '',
                'city' => 'Palikir',
                'province' => 'Micronesia',
                'province_code' => 'FM',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '96941',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '388 Brighton Circle Road',
                'address2' => '',
                'city' => 'Saint Cloud',
                'province' => 'Minnesota',
                'province_code' => 'MN',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '56301',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '560 Gorby Lane',
                'address2' => '',
                'city' => 'Brookhaven',
                'province' => 'Mississippi',
                'province_code' => 'MS',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '39601',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '1614 Hillview Street',
                'address2' => '',
                'city' => 'CHESTERFIELD',
                'province' => 'Missouri',
                'province_code' => 'MO',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '63005',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '4597 Coolidge Street',
                'address2' => '',
                'city' => 'Billings',
                'province' => 'Montana',
                'province_code' => 'MT',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '59101',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '3458 Snowbird Lane',
                'address2' => '',
                'city' => 'Colon',
                'province' => 'Nebraska',
                'province_code' => 'NE',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '68018',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '2989 Sunrise Road',
                'address2' => '',
                'city' => 'Las Vegas',
                'province' => 'Nevada',
                'province_code' => 'NV',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '89107',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '2368 Shearwood Forest Drive',
                'address2' => '',
                'city' => 'Manchester',
                'province' => 'New Hampshire',
                'province_code' => 'NH',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '03109',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '4866 Caynor Circle',
                'address2' => '',
                'city' => 'Summit',
                'province' => 'New Jersey',
                'province_code' => 'NJ',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '07901',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '1940 Dola Mine Road',
                'address2' => '',
                'city' => 'ALGODONES',
                'province' => 'New Mexico',
                'province_code' => 'NM',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '87001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '239 Lake Forest Drive',
                'address2' => '',
                'city' => 'Bedford Village',
                'province' => 'New York',
                'province_code' => 'NY',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '10506',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '3403 Hannah Street',
                'address2' => '',
                'city' => 'Franklin',
                'province' => 'North Carolina',
                'province_code' => 'NC',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '28734',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '482 Findley Avenue',
                'address2' => '',
                'city' => 'Edgeley',
                'province' => 'North Dakota',
                'province_code' => 'ND',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '58433',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => 'Saipan International Airport',
                'address2' => '',
                'city' => 'Saipan',
                'province' => 'Northern Mariana Islands',
                'province_code' => 'MP',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '96950',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '166 Irving Road',
                'address2' => '',
                'city' => 'Mansfield',
                'province' => 'Ohio',
                'province_code' => 'OH',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '44902',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '4870 Henry Ford Avenue',
                'address2' => '',
                'city' => 'Sand Springs',
                'province' => 'Oklahoma',
                'province_code' => 'OK',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '74063',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '4311 School Street',
                'address2' => '',
                'city' => 'ANTELOPE',
                'province' => 'Oregon',
                'province_code' => 'OR',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '97001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => 'Main Street Box 189',
                'address2' => '',
                'city' => 'Koror',
                'province' => 'Palau',
                'province_code' => 'PW',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '96940',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '343 Glen Falls Road',
                'address2' => '',
                'city' => 'Jenkintown',
                'province' => 'Pennsylvania',
                'province_code' => 'PA',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '19046',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '1234 Ave ashford apt',
                'address2' => '',
                'city' => 'San Juan',
                'province' => 'Puerto Rico',
                'province_code' => 'PR',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '00907',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '566 Diamond Cove',
                'address2' => '',
                'city' => 'Providence',
                'province' => 'Rhode Island',
                'province_code' => 'RI',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '02903',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '3805 Traction Street',
                'address2' => '',
                'city' => 'Greenville',
                'province' => 'South Carolina',
                'province_code' => 'SC',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '29601',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '430 Ryan Road',
                'address2' => '',
                'city' => 'Sioux Falls',
                'province' => 'South Dakota',
                'province_code' => 'SD',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '57102',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '318 Hidden Pond Road',
                'address2' => '',
                'city' => 'Dickson',
                'province' => 'Tennessee',
                'province_code' => 'TN',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '37055',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '3291 Sundown Lane',
                'address2' => '',
                'city' => 'Austin',
                'province' => 'Texas',
                'province_code' => 'TX',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '78759',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '166, East End Road',
                'address2' => '',
                'city' => 'Saint Croix',
                'province' => 'U.S. Virgin Islands',
                'province_code' => 'VI',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '00801',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'address1' => '3812 Hickory Street',
                'address2' => '',
                'city' => 'Salt Lake City',
                'province' => 'Utah',
                'province_code' => 'UT',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '84104',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '640 Stroop Hill Road',
                'address2' => '',
                'city' => 'WHITE RIVER JUNCTION',
                'province' => 'Vermont',
                'province_code' => 'VT',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '05001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '3132 Tenmile',
                'address2' => '',
                'city' => 'Newport News',
                'province' => 'Virginia',
                'province_code' => 'VA',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '23602',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '2373 Stockert Hollow Road',
                'address2' => '',
                'city' => 'Bothell',
                'province' => 'Washington',
                'province_code' => 'WA',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '98011',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '1667 K street NW',
                'address2' => '',
                'city' => 'Washington',
                'province' => 'Washington DC',
                'province_code' => 'DC',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '20006',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '4736 Kelly Drive',
                'address2' => '',
                'city' => 'East Lynn',
                'province' => 'West Virginia',
                'province_code' => 'WV',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '25512',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '699 Taylor Street',
                'address2' => '',
                'city' => 'ADELL',
                'province' => 'Wisconsin',
                'province_code' => 'WI',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '53001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '5016 Hanifan Lane',
                'address2' => '',
                'city' => 'CHEYENNE',
                'province' => 'Wyoming',
                'province_code' => 'WY',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '82001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '',
                'address2' => '',
                'city' => '',
                'province' => 'Armed Forces Americas',
                'province_code' => 'AA',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '',
                'address2' => '',
                'city' => '',
                'province' => 'Armed Forces Europe',
                'province_code' => 'AE',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'address1' => '',
                'address2' => '',
                'city' => '',
                'province' => 'Armed Forces Pacific',
                'province_code' => 'AP',
                'country' => 'United States',
                'country_code' => 'US',
                'zip' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        Jurisdictions::insert($jurisdictions);
    }
}
